# Let NetworkManager manage all devices on this system
network:
  version: 2
  renderer: NetworkManager
  ethernets:
    eth0:
      addresses:
      - 10.0.0.5/24
      gateway4: 10.0.0.1
      nameservers:
        addresses:
        - 8.8.8.8
        search:
        - 8.8.4.4